### ISSUE TITLE
Faild to load plugin

### ISSUE THREAD

**Issue by oghostly** [Mourdraug/FanControl.AsusWMI#8]
![260742934c964e9cb808866afa4e9899](https://github.com/Mourdraug/FanControl.AsusWMI/assets/150204858/942d14cb-ac4a-4d1d-96b0-4c4f43dcb6c3)

I get this error after copying the dll into the plugin folder and restarting fan control

**Comment by avnerse3** [comment]
right-click the dll file and select properties.
in the first panel (general) at the very bottom there should be a checkbox - warning this dll is from another computer - select it and click apply.

**Comment by oghostly** [comment]
> right-click the dll file and select properties. in the first panel (general) at the very bottom there should be a checkbox - warning this dll is from another computer - select it and click apply.

Unfortunately now its not loading the plugin at all

**Comment by HartLarsson** [comment]
same problem here... the plugin is not even detected in the list

![image](https://github.com/Mourdraug/FanControl.AsusWMI/assets/16102074/1287037b-4423-4acc-9403-1c38d19b732c)

**Comment by oghostly** [comment]
> same problem here... the plugin is not even detected in the list
> 
> ![image](https://private-user-images.githubusercontent.com/16102074/290602821-1287037b-4423-4acc-9403-1c38d19b732c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Nzc3OTQsIm5iZiI6MTcwMjU3NzQ5NCwicGF0aCI6Ii8xNjEwMjA3NC8yOTA2MDI4MjEtMTI4NzAzN2ItNDQyMy00YWNjLTk0MDMtMWMzOGQxOWI3MzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE4MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmY2VkNDJhNTljNmQyMmY2MTQ5ZjczOGZjOGI5MzRkMzVmZDhmOTVmOTMzN2ZlY2RiZGQ2NDM1ZWEyNjJiYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xfe5wGaP95QEhL3PdRNt0Fnf2HJTopMMXrKTb4b8uow)

I had it in the root folder at first forgetting about the plugin folder but it didn’t make a difference

**Comment by NolonQ** [comment]
Same problem...

![Capture](https://github.com/Mourdraug/FanControl.AsusWMI/assets/149939392/a1c5c2a8-f4c4-4943-8b5d-056ec5102bd5)

**Comment by oghostly** [comment]
> Same problem...
> 
> ![Capture](https://private-user-images.githubusercontent.com/149939392/294787293-a1c5c2a8-f4c4-4943-8b5d-056ec5102bd5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NzE3MjksIm5iZiI6MTcwNDY3MTQyOSwicGF0aCI6Ii8xNDk5MzkzOTIvMjk0Nzg3MjkzLWExYzVjMmE4LWY0YzQtNDk0My04YjVkLTA1NmVjNTEwMmJkNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QyMzUwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWE2MjVlNDBlNzczMGU3YTM4NWI2ZTE3OTQxNDM4Y2M3MTljN2MyZmQ3Mjc1ZDZhMDhjMmZiZDM3MWIyZGZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u-JgGD0FFFxkQ6_5iXTDkKQl8IYo4RucS4cjxKvxmto)

I still have yet to figure this out is it something with iplugin im missing possibly?

**Comment by joridiculous** [comment]
got the same failed to load plugin error here (not exclusive for this plugin)
Failed to load plugin FanControl.AsusWMI.dll. Make sure the plugin's dll is unblocked in its properties.
04/04/2024 01:17:09: System.IO.FileLoadException: Could not load file or assembly 'file:///<path>FanControl\Plugins\FanControl.AsusWMI.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

It is "unblocked" in properties.
Here's more from the log: (full path removed for length and whatnot)
File name: 'file:///<path>FanControl\Plugins\FanControl.AsusWMI.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at FanControl.Domain.PluginService.LoadAssembly(FileInfo dll)

**Comment by moadlouni** [comment]
> right-click the dll file and select properties. in the first panel (general) at the very bottom there should be a checkbox - warning this dll is from another computer - select it and click apply.

I clicked "unblock" checkbox at the bottom of the general tab and then placed the FanControl.AsusWMI.dll in the Plugins folder. Closed fancontrol desktop application and reopened it. No more error. Plugin information is being loaded and displayed accurately(I believe).

Snippet for reference(settings tab): 
![image](https://github.com/user-attachments/assets/47261569-f61b-47eb-bcd8-c0c4a045aae4)
